#!/bin/sh

if [[ "$1" = "-d" ]]
then
  CCC="/home/crane/workspace/clocking/target/debug/clocking --file /tmp/tracking.db"
  echo "Cmd: $CCC"
else
  CCC="/home/crane/.cargo/bin/clocking --file /mnt/nas/home/data/tracking.db"
fi

signaldw() {
	pkill -RTMIN+11 dwmblocks
}

case $(printf "start\nfinish\nongoing\n" | dmenu -p "Action: ") in
  start)
    title=$($CCC titles -n 10 -i | dmenu -p "Title: ");
    title=${title#*: };
    [[ -n "$title" ]] && $CCC start -n "$title" &&\
		notify-send -t 3000 "Started:" "$title" && signaldw;;
  finish) $CCC finish -a && signaldw;;
  ongoing)
    ongoing=$($CCC ongoing);
    notify-send -t 5000 "Ongoing:" "$ongoing" ;;
esac

